### ISSUE TITLE
animation in css

### ISSUE THREAD

**Issue by fabioricali** [dozjs/doz#18]
The component style does not support the short definition like: 

```css
<style>
.my-class {
    animation: 1s blink ease infinite;
}
</style>
```

this works:

```css
<style>
.my-class {
    animation-name: blink;
    animation-duration: 1s;
    animation-timing-function: ease;
    animation-iteration-count: infinite;
}
</style>
```
